version: '3'

name: 'todo'

services:
  db:
    container_name: db
    image: postgres:16.2
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: